Schooly/Schooly/Controllers/EnrollmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Schooly.DAL;
using Schooly.Models;

namespace Schooly.Controllers
{
    public class EnrollmentsController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Enrollments
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(enrollments.ToList());
        }

        // GET: Enrollments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollments/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title");
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentID,CourseID,StudentID,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnrollmentID,CourseID,StudentID,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Schooly/Schooly/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Schooly.DAL;
using Schooly.Models;

namespace Schooly.Controllers
{
    public class PlacesController : Controller
    {
        private SchoolContext db = new SchoolContext();

        private readonly JavaScriptSerializer _jsonSerializer;

        public PlacesController()
        {
            _jsonSerializer = new JavaScriptSerializer();
        }

        // GET: Places
        public ActionResult Index(string searchString)
        {
            var places = from s in db.Places
                          select s;

            List<PlacesInSchool> retVal = db.Places.ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                places = places.Where(s => s.PlaceName.Contains(searchString)
                                       || s.GeoLat.ToString().Contains(searchString)
                                       || s.GeoLong.ToString().Contains(searchString));

                retVal = places.ToList();
            }

            return View(retVal);
        }

        public string GetAllPlaces()
        {
            return _jsonSerializer.Serialize(DAL.PlacesDB.GetSchoolPlaces());
        }
    }
}

Schooly/Schooly/Views/Places/Index.cshtml
@model IEnumerable<Schooly.Models.PlacesInSchool>
@{
    ViewBag.Title = "Places In Schooly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Students addresses</h2>

<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>

<style>
    #map_canvas img {
        max-width: none;
    }
</style>

<style>
    .infoDiv {
        height: 200px;
        width: 300px;
        -webkit-user-select: none;
        background-color: white;
    }
</style>

@if (this.User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<p>
    @Html.ActionLink("Enrollment", "Index", "Enrollments")
</p>

@using (Html.BeginForm())
{
    <p>
        Search: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GeoLat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GeoLong)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlaceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GeoLat)
            </td>
            <th>
                @Html.DisplayFor(modelItem => item.GeoLong)
            </th>
            <td>
                @if (this.User.IsInRole("admin"))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) <text> | </text>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
            </td>
        </tr>
    }

</table>

<div id="map_canvas" style="height: 400px"></div>

<br /><br />

    @section scripts {
        <script type="text/javascript">
            $(function () {
                google.maps.visualRefresh = true;
                var mapOptions = {
                    zoom: 11,
                    center: new google.maps.LatLng(31.8500000, 34.7817680),
                    mapTypeId: google.maps.MapTypeId.G_NORMAL_MAP
                };
                var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
                $.getJSON("../Places/GetAllPlaces", function (getAllPlaces) {
                    for (var i = 0; i < getAllPlaces.length; i++) {
                        var marker = new google.maps.Marker({
                            'position': new google.maps.LatLng(getAllPlaces[i]["GeoLat"], getAllPlaces[i]["GeoLong"]),
                            'map': map,
                            'title': getAllPlaces[i]["PlaceName"]
                        });

                        var content = "<div><h2>" + getAllPlaces[i]["PlaceName"] + "</h4></div>";
                        bindInfoWindow(marker, map, new google.maps.InfoWindow(), content);
                    }
                });

                $('.loading').hide();
            });

            function bindInfoWindow(marker, map, infowindow, html) {
                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.setContent(html);
                    infowindow.open(map, marker);
                });
            }
        </script>
    }