Schooly/Schooly/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Schooly.Controllers
{
    public class HomeController : Controller
    {
        public static bool IsAdmin = false;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Schooly/Schooly/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Schooly.DAL;
using Schooly.Models;

namespace Schooly.Controllers
{
    public class StatisticsController : Controller
    {
        private SchoolContext db = new SchoolContext();

        private void calculateGpa(Student student)
        {
            double curScore = 0;
            int totalCredits = 0;


            foreach (Enrollment curEnroll in student.Enrollments)
            {
                if (curEnroll.Grade != null)
                {
                    curScore += getNumGrade(curEnroll.Grade) * curEnroll.Course.Credits;
                    totalCredits += curEnroll.Course.Credits;
                }
            }

            if (student.Enrollments != null)
            {
                student.Gpa = Math.Round(curScore / totalCredits, 2);
            }
        }

        private double getNumGrade(Grade? curGrade)
        {
            double retVal = 0;

            switch (curGrade)
            {
                case Grade.A:
                    retVal = 4.0;
                    break;

                case Grade.B:
                    retVal = 3.0;
                    break;

                case Grade.C:
                    retVal = 2.0;
                    break;

                case Grade.D:
                    retVal = 1.0;
                    break;

                case Grade.F:
                    retVal = 0.0;
                    break;
                default:
                    break;
            }

            return (retVal);
        }

        //GET: Statistics
        public ActionResult Index(string searchString)
        {
            var studentsAssignedToCourses =
                (from c in db.Courses
                 join e in db.Enrollments on c.CourseID equals e.CourseID
                 join s in db.Students on e.StudentID equals s.ID into q1
                 group q1 by c.Title into q2
                 select new AssignmentViewModel
                 {
                     CourseName = q2.Key,
                     NumOfStudents = q2.Count(),
                     StudentsNames =
                     (
                        from enr in db.Enrollments
                        where enr.Course.Title == q2.Key
                        select new StudentInfo
                        {
                            FName = enr.Student.FirstMidName,
                            LName = enr.Student.LastName
                        }).ToList()
                 }).ToList();

            #region OLD
            //from s in db.Students
            //    join e in db.Enrollments on s.ID equals e.StudentID
            //    join c in db.Courses on e.CourseID equals c.CourseID into q1
            //    group q1 by s.LastName

            //List<Student> retVal = students.ToList<Student>();

            //foreach (Student curStudent in retVal)
            //{
            //    calculateGpa(curStudent);
            //}

            //retVal = retVal.Distinct<Student>(new CompareStudents()).ToList<Student>(); 
            #endregion

            return View(studentsAssignedToCourses);
        }

        public ActionResult CalculusAge()
        {
            return View();
        }

        public ActionResult StudentCity()
        {
            return View();
        }

        //public string GetCalculsAges()
        //{
        //    return "age,population\r\n" + String.Join(Environment.NewLine, AuthorRepository.GetAllAuthors()
        //        .Select(x => x.Name + " - " + x.BooksWrittenBy.Count + "," + x.BooksWrittenBy.Count));
        //}

        //public string GetStudentsGradesCount()
        //{
        //    string a = "letter	frequency\r\n" + String.Join(Environment.NewLine, DAL.CalculusAgeDB.GetAllEnrollments().GroupBy(x => x.Grade)
        //          .Select(x => x.Key + "\t" + x.Count()));
        //    return a;
        //}
    }
}

Schooly/Schooly/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Schooly.DAL;
using Schooly.Models;
using Microsoft.Ajax.Utilities;
using System.Web.Script.Serialization;

namespace Schooly.Controllers
{
    public class StudentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        private readonly JavaScriptSerializer _jsonSerializer;

        private void calculateGpa(Student student)
        {
            double curScore = 0;
            int totalCredits = 0;


            foreach (Enrollment curEnroll in student.Enrollments)
            {
                if (curEnroll.Grade != null)
                {
                    curScore += getNumGrade(curEnroll.Grade) * curEnroll.Course.Credits;
                    totalCredits += curEnroll.Course.Credits;
                }
            }

            if (student.Enrollments != null)
            {
                student.Gpa = Math.Round(curScore / totalCredits, 2);
            }
        }

        private double getNumGrade(Grade? curGrade)
        {
            double retVal = 0;

            switch (curGrade)
            {
                case Grade.A:
                    retVal = 4.0;
                    break;

                case Grade.B:
                    retVal = 3.0;
                    break;

                case Grade.C:
                    retVal = 2.0;
                    break;

                case Grade.D:
                    retVal = 1.0;
                    break;

                case Grade.F:
                    retVal = 0.0;
                    break;
                default:
                    break;
            }

            return (retVal);
        }

        private SelectList GetDistinctFNameList(List<Student> list)
        {
            // Creating a distinct (by first name) student list
            List<Student> distintStudents =
                list.Distinct<Student>(new CompareStudents()).ToList<Student>();

            // Creating the list items for the student drop down list
            IEnumerable<SelectListItem> studentListItems =
                distintStudents.AsEnumerable().Select(
                c => new SelectListItem
                {
                    Text = c.FirstMidName,
                    Value = c.ID.ToString(),
                    Selected = false
                });

            // Creating the select list
            SelectList studentsList = new SelectList(studentListItems, "Value", "Text");

            return studentsList;
        }

        private SelectList GetDistinctGpaList(List<Student> list)
        {
            // Creating a distinct (by Gpa) student list
            List<Student> distintGpaStudents =
                list.DistinctBy(x => x.Gpa).ToList<Student>();

            // Creating the list items for the student drop down list
            IEnumerable<SelectListItem> studentGpaListItems =
                distintGpaStudents.AsEnumerable().Select(
                c => new SelectListItem
                {
                    Text = c.Gpa.ToString(),
                    Value = c.ID.ToString(),
                    Selected = false
                });

            // Creating the select list
            SelectList studentsList = new SelectList(studentGpaListItems, "Value", "Text");

            return studentsList;
        }

        private SelectList GetDistinctCityList(List<Student> list)
        {
            // Creating a distinct (by City) student list
            List<Student> distintCityStudents =
                list.DistinctBy(x => x.City).ToList<Student>();

            // Creating the list items for the student drop down list
            IEnumerable<SelectListItem> studentCityListItems =
                distintCityStudents.AsEnumerable().Select(
                c => new SelectListItem
                {
                    Text = c.City.ToString(),
                    Value = c.ID.ToString(),
                    Selected = false
                });

            // Creating the select list
            SelectList studentsList = new SelectList(studentCityListItems, "Value", "Text");

            return studentsList;
        }

        public StudentController()
        {
            _jsonSerializer = new JavaScriptSerializer();
            ViewBag.IsAdminLogged = System.Web.HttpContext.Current.Session["IsAdminLogged"];
        }

        public string GetStudents(string firstName = null, string lastName = null, double? gpa = null, int? yearsInSchool = null)
        {
            return _jsonSerializer.Serialize(StudentDAL.GetFilteredStudents(firstName, lastName, gpa, yearsInSchool));
        }

        // GET: Student
        public ActionResult Index(string searchString)
        {
            var students = from s in db.Students
                           select s;

            List<Student> retVal = db.Students.ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.Contains(searchString)
                                       || s.FirstMidName.Contains(searchString)
                                       || s.City.Contains(searchString)
                                       || s.Age.ToString().Contains(searchString));

                retVal = students.ToList<Student>();
            }

            foreach (Student curStudent in retVal)
            {
                calculateGpa(curStudent);
            }

            // Getting the Distinct student list
            SelectList studentsFNameList = GetDistinctFNameList(retVal);

            // Inserting the studentList to the View Bag
            ViewBag.StudentsFNameList = studentsFNameList;

            // Getting the Distinct gpa list
            SelectList studentGpaList = GetDistinctGpaList(retVal);

            // Inserting the gpa list to the View Bag
            ViewBag.GpaList = studentGpaList;

            // Getting the Distrinct city list
            SelectList studentCityList = GetDistinctCityList(retVal);

            // Inserting the city list the View Bag
            ViewBag.CityList = studentCityList;

            return View(retVal);
        }

        // GET: Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LastName,FirstMidName,Age,City,YearsInSchool,EnrollmentDate")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Student/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstMidName,Age,City,YearsInSchool,EnrollmentDate")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        [HttpPost]
        public ActionResult UpdateTable()
        {
            return View();
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }

    public class CompareStudents : IEqualityComparer<Student>
    {
        public bool Equals(Student x, Student y)
        {
            return x.FirstMidName == y.FirstMidName;
        }

        public int GetHashCode(Student codeh)
        {
            return codeh.GetHashCode();
        }
    }
}

Schooly/Schooly/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Schooly/Schooly/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Schooly/Schooly/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Schooly</h1>
</div>
<style>
    .dani {
        width: 150px;
        height: 100px;
        background: red;
        -webkit-transition: width 2s; /* For Safari 3.1 to 6.0 */
        transition: width 2s;
    }

        .dani:hover {
            width: 300px;
        }
</style>
<iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="http://forecast.io/embed/#lat=32.06632&lon=34.77782&name=Tel%20Aviv&units=ca"> </iframe>
<div class="dani">
    <header>
        <canvas id="myCanvas" width="300" height="100" style="border:1px solid #d3d3d3;">
            Your browser does not support the HTML5 canvas tag.
        </canvas>
    </header>
</div>
<body>
    <div class="row">
        <div class="col-md-4">
            <video controls="controls" width="300" height="240">
                <source src="/Images/shauli.m4v" type="video/mp4" />
                Your browser does not support the video tag.
            </video>
            <p>
                Schooly is one of the top 5 schools administration systemin the world.
                All our students like to come every morning to school.
            </p>
            <div class="newspaper">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
            </div>
        </div>
        <aside>
            <section>
                <h3>Aside Title</h3>
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Places", "Index", "Places")</li>
                </ul>
                </section>
            <section> 
                <h3>Dani</h3>
                <ul>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                    </ul>
            </section>
            <section> 
                <h3>Roy</h3> 
                <ul>
                    <li>@Html.ActionLink("Students Grades", "StudentCity", "Statistics")</li>
                    <li>@Html.ActionLink("Calculus Age statistic", "CalculusAge", "Statistics")</li>
                </ul>
</section>
</aside>
    </div>
    <script>
        var c = document.getElementById("myCanvas");
        var ctx = c.getContext("2d");
        ctx.font = "30px Arial";
        ctx.fillText("Welcome to Schooly", 10, 50);
    </script>
</body>